version: '3.12'

services:
  airflow:
    image: apache/airflow:2.7.2
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./Flight_Price_Dataset_of_Bangladesh.csv:/opt/airflow/Flight_Price_Dataset_of_Bangladesh.csv
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
               airflow scheduler & airflow webserver"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: flightdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: flight
      MYSQL_PASSWORD: flight
    ports:
      - "3307:3306"
    volumes:
      - mysql-db-volume:/var/lib/mysql

volumes:
  postgres-db-volume:
  mysql-db-volume:
